// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/Rshadow.h"
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// shadow_plus_Tensor_Tensor
Rcpp::S4 shadow_plus_Tensor_Tensor(Rcpp::S4 left, Rcpp::S4 right);
RcppExport SEXP _Rshadow_shadow_plus_Tensor_Tensor(SEXP leftSEXP, SEXP rightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type left(leftSEXP);
    Rcpp::traits::input_parameter< Rcpp::S4 >::type right(rightSEXP);
    rcpp_result_gen = Rcpp::wrap(shadow_plus_Tensor_Tensor(left, right));
    return rcpp_result_gen;
END_RCPP
}
// shadow_plus_Tensor_Spy
Rcpp::S4 shadow_plus_Tensor_Spy(Rcpp::S4 left, Rcpp::S4 right);
RcppExport SEXP _Rshadow_shadow_plus_Tensor_Spy(SEXP leftSEXP, SEXP rightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type left(leftSEXP);
    Rcpp::traits::input_parameter< Rcpp::S4 >::type right(rightSEXP);
    rcpp_result_gen = Rcpp::wrap(shadow_plus_Tensor_Spy(left, right));
    return rcpp_result_gen;
END_RCPP
}
// shadow_plus_Spy_Tensor
Rcpp::S4 shadow_plus_Spy_Tensor(Rcpp::S4 left, Rcpp::S4 right);
RcppExport SEXP _Rshadow_shadow_plus_Spy_Tensor(SEXP leftSEXP, SEXP rightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type left(leftSEXP);
    Rcpp::traits::input_parameter< Rcpp::S4 >::type right(rightSEXP);
    rcpp_result_gen = Rcpp::wrap(shadow_plus_Spy_Tensor(left, right));
    return rcpp_result_gen;
END_RCPP
}
// shadow_plus_Spy_Spy
Rcpp::S4 shadow_plus_Spy_Spy(Rcpp::S4 left, Rcpp::S4 right);
RcppExport SEXP _Rshadow_shadow_plus_Spy_Spy(SEXP leftSEXP, SEXP rightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type left(leftSEXP);
    Rcpp::traits::input_parameter< Rcpp::S4 >::type right(rightSEXP);
    rcpp_result_gen = Rcpp::wrap(shadow_plus_Spy_Spy(left, right));
    return rcpp_result_gen;
END_RCPP
}
// shadow_minus_Tensor_Tensor
Rcpp::S4 shadow_minus_Tensor_Tensor(Rcpp::S4 left, Rcpp::S4 right);
RcppExport SEXP _Rshadow_shadow_minus_Tensor_Tensor(SEXP leftSEXP, SEXP rightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type left(leftSEXP);
    Rcpp::traits::input_parameter< Rcpp::S4 >::type right(rightSEXP);
    rcpp_result_gen = Rcpp::wrap(shadow_minus_Tensor_Tensor(left, right));
    return rcpp_result_gen;
END_RCPP
}
// shadow_minus_Tensor_Spy
Rcpp::S4 shadow_minus_Tensor_Spy(Rcpp::S4 left, Rcpp::S4 right);
RcppExport SEXP _Rshadow_shadow_minus_Tensor_Spy(SEXP leftSEXP, SEXP rightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type left(leftSEXP);
    Rcpp::traits::input_parameter< Rcpp::S4 >::type right(rightSEXP);
    rcpp_result_gen = Rcpp::wrap(shadow_minus_Tensor_Spy(left, right));
    return rcpp_result_gen;
END_RCPP
}
// shadow_minus_Spy_Tensor
Rcpp::S4 shadow_minus_Spy_Tensor(Rcpp::S4 left, Rcpp::S4 right);
RcppExport SEXP _Rshadow_shadow_minus_Spy_Tensor(SEXP leftSEXP, SEXP rightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type left(leftSEXP);
    Rcpp::traits::input_parameter< Rcpp::S4 >::type right(rightSEXP);
    rcpp_result_gen = Rcpp::wrap(shadow_minus_Spy_Tensor(left, right));
    return rcpp_result_gen;
END_RCPP
}
// shadow_minus_Spy_Spy
Rcpp::S4 shadow_minus_Spy_Spy(Rcpp::S4 left, Rcpp::S4 right);
RcppExport SEXP _Rshadow_shadow_minus_Spy_Spy(SEXP leftSEXP, SEXP rightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type left(leftSEXP);
    Rcpp::traits::input_parameter< Rcpp::S4 >::type right(rightSEXP);
    rcpp_result_gen = Rcpp::wrap(shadow_minus_Spy_Spy(left, right));
    return rcpp_result_gen;
END_RCPP
}
// shadow_multiplies_Tensor_Tensor
Rcpp::S4 shadow_multiplies_Tensor_Tensor(Rcpp::S4 left, Rcpp::S4 right);
RcppExport SEXP _Rshadow_shadow_multiplies_Tensor_Tensor(SEXP leftSEXP, SEXP rightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type left(leftSEXP);
    Rcpp::traits::input_parameter< Rcpp::S4 >::type right(rightSEXP);
    rcpp_result_gen = Rcpp::wrap(shadow_multiplies_Tensor_Tensor(left, right));
    return rcpp_result_gen;
END_RCPP
}
// shadow_multiplies_Tensor_Spy
Rcpp::S4 shadow_multiplies_Tensor_Spy(Rcpp::S4 left, Rcpp::S4 right);
RcppExport SEXP _Rshadow_shadow_multiplies_Tensor_Spy(SEXP leftSEXP, SEXP rightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type left(leftSEXP);
    Rcpp::traits::input_parameter< Rcpp::S4 >::type right(rightSEXP);
    rcpp_result_gen = Rcpp::wrap(shadow_multiplies_Tensor_Spy(left, right));
    return rcpp_result_gen;
END_RCPP
}
// shadow_multiplies_Spy_Tensor
Rcpp::S4 shadow_multiplies_Spy_Tensor(Rcpp::S4 left, Rcpp::S4 right);
RcppExport SEXP _Rshadow_shadow_multiplies_Spy_Tensor(SEXP leftSEXP, SEXP rightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type left(leftSEXP);
    Rcpp::traits::input_parameter< Rcpp::S4 >::type right(rightSEXP);
    rcpp_result_gen = Rcpp::wrap(shadow_multiplies_Spy_Tensor(left, right));
    return rcpp_result_gen;
END_RCPP
}
// shadow_multiplies_Spy_Spy
Rcpp::S4 shadow_multiplies_Spy_Spy(Rcpp::S4 left, Rcpp::S4 right);
RcppExport SEXP _Rshadow_shadow_multiplies_Spy_Spy(SEXP leftSEXP, SEXP rightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type left(leftSEXP);
    Rcpp::traits::input_parameter< Rcpp::S4 >::type right(rightSEXP);
    rcpp_result_gen = Rcpp::wrap(shadow_multiplies_Spy_Spy(left, right));
    return rcpp_result_gen;
END_RCPP
}
// shadow_divides_Tensor_Tensor
Rcpp::S4 shadow_divides_Tensor_Tensor(Rcpp::S4 left, Rcpp::S4 right);
RcppExport SEXP _Rshadow_shadow_divides_Tensor_Tensor(SEXP leftSEXP, SEXP rightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type left(leftSEXP);
    Rcpp::traits::input_parameter< Rcpp::S4 >::type right(rightSEXP);
    rcpp_result_gen = Rcpp::wrap(shadow_divides_Tensor_Tensor(left, right));
    return rcpp_result_gen;
END_RCPP
}
// shadow_divides_Tensor_Spy
Rcpp::S4 shadow_divides_Tensor_Spy(Rcpp::S4 left, Rcpp::S4 right);
RcppExport SEXP _Rshadow_shadow_divides_Tensor_Spy(SEXP leftSEXP, SEXP rightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type left(leftSEXP);
    Rcpp::traits::input_parameter< Rcpp::S4 >::type right(rightSEXP);
    rcpp_result_gen = Rcpp::wrap(shadow_divides_Tensor_Spy(left, right));
    return rcpp_result_gen;
END_RCPP
}
// shadow_divides_Spy_Tensor
Rcpp::S4 shadow_divides_Spy_Tensor(Rcpp::S4 left, Rcpp::S4 right);
RcppExport SEXP _Rshadow_shadow_divides_Spy_Tensor(SEXP leftSEXP, SEXP rightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type left(leftSEXP);
    Rcpp::traits::input_parameter< Rcpp::S4 >::type right(rightSEXP);
    rcpp_result_gen = Rcpp::wrap(shadow_divides_Spy_Tensor(left, right));
    return rcpp_result_gen;
END_RCPP
}
// shadow_divides_Spy_Spy
Rcpp::S4 shadow_divides_Spy_Spy(Rcpp::S4 left, Rcpp::S4 right);
RcppExport SEXP _Rshadow_shadow_divides_Spy_Spy(SEXP leftSEXP, SEXP rightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type left(leftSEXP);
    Rcpp::traits::input_parameter< Rcpp::S4 >::type right(rightSEXP);
    rcpp_result_gen = Rcpp::wrap(shadow_divides_Spy_Spy(left, right));
    return rcpp_result_gen;
END_RCPP
}
// shadow_less_Tensor_Tensor
Rcpp::S4 shadow_less_Tensor_Tensor(Rcpp::S4 left, Rcpp::S4 right);
RcppExport SEXP _Rshadow_shadow_less_Tensor_Tensor(SEXP leftSEXP, SEXP rightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type left(leftSEXP);
    Rcpp::traits::input_parameter< Rcpp::S4 >::type right(rightSEXP);
    rcpp_result_gen = Rcpp::wrap(shadow_less_Tensor_Tensor(left, right));
    return rcpp_result_gen;
END_RCPP
}
// shadow_less_Tensor_Spy
Rcpp::S4 shadow_less_Tensor_Spy(Rcpp::S4 left, Rcpp::S4 right);
RcppExport SEXP _Rshadow_shadow_less_Tensor_Spy(SEXP leftSEXP, SEXP rightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type left(leftSEXP);
    Rcpp::traits::input_parameter< Rcpp::S4 >::type right(rightSEXP);
    rcpp_result_gen = Rcpp::wrap(shadow_less_Tensor_Spy(left, right));
    return rcpp_result_gen;
END_RCPP
}
// shadow_less_Spy_Tensor
Rcpp::S4 shadow_less_Spy_Tensor(Rcpp::S4 left, Rcpp::S4 right);
RcppExport SEXP _Rshadow_shadow_less_Spy_Tensor(SEXP leftSEXP, SEXP rightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type left(leftSEXP);
    Rcpp::traits::input_parameter< Rcpp::S4 >::type right(rightSEXP);
    rcpp_result_gen = Rcpp::wrap(shadow_less_Spy_Tensor(left, right));
    return rcpp_result_gen;
END_RCPP
}
// shadow_less_Spy_Spy
Rcpp::S4 shadow_less_Spy_Spy(Rcpp::S4 left, Rcpp::S4 right);
RcppExport SEXP _Rshadow_shadow_less_Spy_Spy(SEXP leftSEXP, SEXP rightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type left(leftSEXP);
    Rcpp::traits::input_parameter< Rcpp::S4 >::type right(rightSEXP);
    rcpp_result_gen = Rcpp::wrap(shadow_less_Spy_Spy(left, right));
    return rcpp_result_gen;
END_RCPP
}
// shadow_less_equal_Tensor_Tensor
Rcpp::S4 shadow_less_equal_Tensor_Tensor(Rcpp::S4 left, Rcpp::S4 right);
RcppExport SEXP _Rshadow_shadow_less_equal_Tensor_Tensor(SEXP leftSEXP, SEXP rightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type left(leftSEXP);
    Rcpp::traits::input_parameter< Rcpp::S4 >::type right(rightSEXP);
    rcpp_result_gen = Rcpp::wrap(shadow_less_equal_Tensor_Tensor(left, right));
    return rcpp_result_gen;
END_RCPP
}
// shadow_less_equal_Tensor_Spy
Rcpp::S4 shadow_less_equal_Tensor_Spy(Rcpp::S4 left, Rcpp::S4 right);
RcppExport SEXP _Rshadow_shadow_less_equal_Tensor_Spy(SEXP leftSEXP, SEXP rightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type left(leftSEXP);
    Rcpp::traits::input_parameter< Rcpp::S4 >::type right(rightSEXP);
    rcpp_result_gen = Rcpp::wrap(shadow_less_equal_Tensor_Spy(left, right));
    return rcpp_result_gen;
END_RCPP
}
// shadow_less_equal_Spy_Tensor
Rcpp::S4 shadow_less_equal_Spy_Tensor(Rcpp::S4 left, Rcpp::S4 right);
RcppExport SEXP _Rshadow_shadow_less_equal_Spy_Tensor(SEXP leftSEXP, SEXP rightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type left(leftSEXP);
    Rcpp::traits::input_parameter< Rcpp::S4 >::type right(rightSEXP);
    rcpp_result_gen = Rcpp::wrap(shadow_less_equal_Spy_Tensor(left, right));
    return rcpp_result_gen;
END_RCPP
}
// shadow_less_equal_Spy_Spy
Rcpp::S4 shadow_less_equal_Spy_Spy(Rcpp::S4 left, Rcpp::S4 right);
RcppExport SEXP _Rshadow_shadow_less_equal_Spy_Spy(SEXP leftSEXP, SEXP rightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type left(leftSEXP);
    Rcpp::traits::input_parameter< Rcpp::S4 >::type right(rightSEXP);
    rcpp_result_gen = Rcpp::wrap(shadow_less_equal_Spy_Spy(left, right));
    return rcpp_result_gen;
END_RCPP
}
// shadow_greater_Tensor_Tensor
Rcpp::S4 shadow_greater_Tensor_Tensor(Rcpp::S4 left, Rcpp::S4 right);
RcppExport SEXP _Rshadow_shadow_greater_Tensor_Tensor(SEXP leftSEXP, SEXP rightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type left(leftSEXP);
    Rcpp::traits::input_parameter< Rcpp::S4 >::type right(rightSEXP);
    rcpp_result_gen = Rcpp::wrap(shadow_greater_Tensor_Tensor(left, right));
    return rcpp_result_gen;
END_RCPP
}
// shadow_greater_Tensor_Spy
Rcpp::S4 shadow_greater_Tensor_Spy(Rcpp::S4 left, Rcpp::S4 right);
RcppExport SEXP _Rshadow_shadow_greater_Tensor_Spy(SEXP leftSEXP, SEXP rightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type left(leftSEXP);
    Rcpp::traits::input_parameter< Rcpp::S4 >::type right(rightSEXP);
    rcpp_result_gen = Rcpp::wrap(shadow_greater_Tensor_Spy(left, right));
    return rcpp_result_gen;
END_RCPP
}
// shadow_greater_Spy_Tensor
Rcpp::S4 shadow_greater_Spy_Tensor(Rcpp::S4 left, Rcpp::S4 right);
RcppExport SEXP _Rshadow_shadow_greater_Spy_Tensor(SEXP leftSEXP, SEXP rightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type left(leftSEXP);
    Rcpp::traits::input_parameter< Rcpp::S4 >::type right(rightSEXP);
    rcpp_result_gen = Rcpp::wrap(shadow_greater_Spy_Tensor(left, right));
    return rcpp_result_gen;
END_RCPP
}
// shadow_greater_Spy_Spy
Rcpp::S4 shadow_greater_Spy_Spy(Rcpp::S4 left, Rcpp::S4 right);
RcppExport SEXP _Rshadow_shadow_greater_Spy_Spy(SEXP leftSEXP, SEXP rightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type left(leftSEXP);
    Rcpp::traits::input_parameter< Rcpp::S4 >::type right(rightSEXP);
    rcpp_result_gen = Rcpp::wrap(shadow_greater_Spy_Spy(left, right));
    return rcpp_result_gen;
END_RCPP
}
// shadow_greater_equal_Tensor_Tensor
Rcpp::S4 shadow_greater_equal_Tensor_Tensor(Rcpp::S4 left, Rcpp::S4 right);
RcppExport SEXP _Rshadow_shadow_greater_equal_Tensor_Tensor(SEXP leftSEXP, SEXP rightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type left(leftSEXP);
    Rcpp::traits::input_parameter< Rcpp::S4 >::type right(rightSEXP);
    rcpp_result_gen = Rcpp::wrap(shadow_greater_equal_Tensor_Tensor(left, right));
    return rcpp_result_gen;
END_RCPP
}
// shadow_greater_equal_Tensor_Spy
Rcpp::S4 shadow_greater_equal_Tensor_Spy(Rcpp::S4 left, Rcpp::S4 right);
RcppExport SEXP _Rshadow_shadow_greater_equal_Tensor_Spy(SEXP leftSEXP, SEXP rightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type left(leftSEXP);
    Rcpp::traits::input_parameter< Rcpp::S4 >::type right(rightSEXP);
    rcpp_result_gen = Rcpp::wrap(shadow_greater_equal_Tensor_Spy(left, right));
    return rcpp_result_gen;
END_RCPP
}
// shadow_greater_equal_Spy_Tensor
Rcpp::S4 shadow_greater_equal_Spy_Tensor(Rcpp::S4 left, Rcpp::S4 right);
RcppExport SEXP _Rshadow_shadow_greater_equal_Spy_Tensor(SEXP leftSEXP, SEXP rightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type left(leftSEXP);
    Rcpp::traits::input_parameter< Rcpp::S4 >::type right(rightSEXP);
    rcpp_result_gen = Rcpp::wrap(shadow_greater_equal_Spy_Tensor(left, right));
    return rcpp_result_gen;
END_RCPP
}
// shadow_greater_equal_Spy_Spy
Rcpp::S4 shadow_greater_equal_Spy_Spy(Rcpp::S4 left, Rcpp::S4 right);
RcppExport SEXP _Rshadow_shadow_greater_equal_Spy_Spy(SEXP leftSEXP, SEXP rightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type left(leftSEXP);
    Rcpp::traits::input_parameter< Rcpp::S4 >::type right(rightSEXP);
    rcpp_result_gen = Rcpp::wrap(shadow_greater_equal_Spy_Spy(left, right));
    return rcpp_result_gen;
END_RCPP
}
// shadow_pow_Tensor_Tensor
Rcpp::S4 shadow_pow_Tensor_Tensor(Rcpp::S4 left, Rcpp::S4 right);
RcppExport SEXP _Rshadow_shadow_pow_Tensor_Tensor(SEXP leftSEXP, SEXP rightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type left(leftSEXP);
    Rcpp::traits::input_parameter< Rcpp::S4 >::type right(rightSEXP);
    rcpp_result_gen = Rcpp::wrap(shadow_pow_Tensor_Tensor(left, right));
    return rcpp_result_gen;
END_RCPP
}
// shadow_pow_Tensor_Spy
Rcpp::S4 shadow_pow_Tensor_Spy(Rcpp::S4 left, Rcpp::S4 right);
RcppExport SEXP _Rshadow_shadow_pow_Tensor_Spy(SEXP leftSEXP, SEXP rightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type left(leftSEXP);
    Rcpp::traits::input_parameter< Rcpp::S4 >::type right(rightSEXP);
    rcpp_result_gen = Rcpp::wrap(shadow_pow_Tensor_Spy(left, right));
    return rcpp_result_gen;
END_RCPP
}
// shadow_pow_Spy_Tensor
Rcpp::S4 shadow_pow_Spy_Tensor(Rcpp::S4 left, Rcpp::S4 right);
RcppExport SEXP _Rshadow_shadow_pow_Spy_Tensor(SEXP leftSEXP, SEXP rightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type left(leftSEXP);
    Rcpp::traits::input_parameter< Rcpp::S4 >::type right(rightSEXP);
    rcpp_result_gen = Rcpp::wrap(shadow_pow_Spy_Tensor(left, right));
    return rcpp_result_gen;
END_RCPP
}
// shadow_pow_Spy_Spy
Rcpp::S4 shadow_pow_Spy_Spy(Rcpp::S4 left, Rcpp::S4 right);
RcppExport SEXP _Rshadow_shadow_pow_Spy_Spy(SEXP leftSEXP, SEXP rightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type left(leftSEXP);
    Rcpp::traits::input_parameter< Rcpp::S4 >::type right(rightSEXP);
    rcpp_result_gen = Rcpp::wrap(shadow_pow_Spy_Spy(left, right));
    return rcpp_result_gen;
END_RCPP
}
// shadow_dot_Tensor_Tensor
Rcpp::S4 shadow_dot_Tensor_Tensor(Rcpp::S4 left, Rcpp::S4 right);
RcppExport SEXP _Rshadow_shadow_dot_Tensor_Tensor(SEXP leftSEXP, SEXP rightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type left(leftSEXP);
    Rcpp::traits::input_parameter< Rcpp::S4 >::type right(rightSEXP);
    rcpp_result_gen = Rcpp::wrap(shadow_dot_Tensor_Tensor(left, right));
    return rcpp_result_gen;
END_RCPP
}
// shadow_dot_Tensor_Spy
Rcpp::S4 shadow_dot_Tensor_Spy(Rcpp::S4 left, Rcpp::S4 right);
RcppExport SEXP _Rshadow_shadow_dot_Tensor_Spy(SEXP leftSEXP, SEXP rightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type left(leftSEXP);
    Rcpp::traits::input_parameter< Rcpp::S4 >::type right(rightSEXP);
    rcpp_result_gen = Rcpp::wrap(shadow_dot_Tensor_Spy(left, right));
    return rcpp_result_gen;
END_RCPP
}
// shadow_dot_Spy_Tensor
Rcpp::S4 shadow_dot_Spy_Tensor(Rcpp::S4 left, Rcpp::S4 right);
RcppExport SEXP _Rshadow_shadow_dot_Spy_Tensor(SEXP leftSEXP, SEXP rightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type left(leftSEXP);
    Rcpp::traits::input_parameter< Rcpp::S4 >::type right(rightSEXP);
    rcpp_result_gen = Rcpp::wrap(shadow_dot_Spy_Tensor(left, right));
    return rcpp_result_gen;
END_RCPP
}
// shadow_dot_Spy_Spy
Rcpp::S4 shadow_dot_Spy_Spy(Rcpp::S4 left, Rcpp::S4 right);
RcppExport SEXP _Rshadow_shadow_dot_Spy_Spy(SEXP leftSEXP, SEXP rightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type left(leftSEXP);
    Rcpp::traits::input_parameter< Rcpp::S4 >::type right(rightSEXP);
    rcpp_result_gen = Rcpp::wrap(shadow_dot_Spy_Spy(left, right));
    return rcpp_result_gen;
END_RCPP
}
// shadow_sumlogbern_Tensor_Tensor
Rcpp::S4 shadow_sumlogbern_Tensor_Tensor(Rcpp::S4 left, Rcpp::S4 right);
RcppExport SEXP _Rshadow_shadow_sumlogbern_Tensor_Tensor(SEXP leftSEXP, SEXP rightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type left(leftSEXP);
    Rcpp::traits::input_parameter< Rcpp::S4 >::type right(rightSEXP);
    rcpp_result_gen = Rcpp::wrap(shadow_sumlogbern_Tensor_Tensor(left, right));
    return rcpp_result_gen;
END_RCPP
}
// shadow_sumlogbern_Spy_Tensor
Rcpp::S4 shadow_sumlogbern_Spy_Tensor(Rcpp::S4 left, Rcpp::S4 right);
RcppExport SEXP _Rshadow_shadow_sumlogbern_Spy_Tensor(SEXP leftSEXP, SEXP rightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type left(leftSEXP);
    Rcpp::traits::input_parameter< Rcpp::S4 >::type right(rightSEXP);
    rcpp_result_gen = Rcpp::wrap(shadow_sumlogbern_Spy_Tensor(left, right));
    return rcpp_result_gen;
END_RCPP
}
// shadow_matmult_Tensor_Tensor
Rcpp::S4 shadow_matmult_Tensor_Tensor(Rcpp::S4 left, Rcpp::S4 right);
RcppExport SEXP _Rshadow_shadow_matmult_Tensor_Tensor(SEXP leftSEXP, SEXP rightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type left(leftSEXP);
    Rcpp::traits::input_parameter< Rcpp::S4 >::type right(rightSEXP);
    rcpp_result_gen = Rcpp::wrap(shadow_matmult_Tensor_Tensor(left, right));
    return rcpp_result_gen;
END_RCPP
}
// shadow_matmult_Tensor_Spy
Rcpp::S4 shadow_matmult_Tensor_Spy(Rcpp::S4 left, Rcpp::S4 right);
RcppExport SEXP _Rshadow_shadow_matmult_Tensor_Spy(SEXP leftSEXP, SEXP rightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type left(leftSEXP);
    Rcpp::traits::input_parameter< Rcpp::S4 >::type right(rightSEXP);
    rcpp_result_gen = Rcpp::wrap(shadow_matmult_Tensor_Spy(left, right));
    return rcpp_result_gen;
END_RCPP
}
// shadow_matmult_Spy_Tensor
Rcpp::S4 shadow_matmult_Spy_Tensor(Rcpp::S4 left, Rcpp::S4 right);
RcppExport SEXP _Rshadow_shadow_matmult_Spy_Tensor(SEXP leftSEXP, SEXP rightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type left(leftSEXP);
    Rcpp::traits::input_parameter< Rcpp::S4 >::type right(rightSEXP);
    rcpp_result_gen = Rcpp::wrap(shadow_matmult_Spy_Tensor(left, right));
    return rcpp_result_gen;
END_RCPP
}
// shadow_matmult_Spy_Spy
Rcpp::S4 shadow_matmult_Spy_Spy(Rcpp::S4 left, Rcpp::S4 right);
RcppExport SEXP _Rshadow_shadow_matmult_Spy_Spy(SEXP leftSEXP, SEXP rightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type left(leftSEXP);
    Rcpp::traits::input_parameter< Rcpp::S4 >::type right(rightSEXP);
    rcpp_result_gen = Rcpp::wrap(shadow_matmult_Spy_Spy(left, right));
    return rcpp_result_gen;
END_RCPP
}
// shadow_negate_Tensor
Rcpp::S4 shadow_negate_Tensor(Rcpp::S4 x);
RcppExport SEXP _Rshadow_shadow_negate_Tensor(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(shadow_negate_Tensor(x));
    return rcpp_result_gen;
END_RCPP
}
// shadow_negate_Spy
Rcpp::S4 shadow_negate_Spy(Rcpp::S4 x);
RcppExport SEXP _Rshadow_shadow_negate_Spy(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(shadow_negate_Spy(x));
    return rcpp_result_gen;
END_RCPP
}
// shadow_log_Tensor
Rcpp::S4 shadow_log_Tensor(Rcpp::S4 x);
RcppExport SEXP _Rshadow_shadow_log_Tensor(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(shadow_log_Tensor(x));
    return rcpp_result_gen;
END_RCPP
}
// shadow_log_Spy
Rcpp::S4 shadow_log_Spy(Rcpp::S4 x);
RcppExport SEXP _Rshadow_shadow_log_Spy(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(shadow_log_Spy(x));
    return rcpp_result_gen;
END_RCPP
}
// shadow_log1p_Tensor
Rcpp::S4 shadow_log1p_Tensor(Rcpp::S4 x);
RcppExport SEXP _Rshadow_shadow_log1p_Tensor(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(shadow_log1p_Tensor(x));
    return rcpp_result_gen;
END_RCPP
}
// shadow_log1p_Spy
Rcpp::S4 shadow_log1p_Spy(Rcpp::S4 x);
RcppExport SEXP _Rshadow_shadow_log1p_Spy(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(shadow_log1p_Spy(x));
    return rcpp_result_gen;
END_RCPP
}
// shadow_log1m_Tensor
Rcpp::S4 shadow_log1m_Tensor(Rcpp::S4 x);
RcppExport SEXP _Rshadow_shadow_log1m_Tensor(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(shadow_log1m_Tensor(x));
    return rcpp_result_gen;
END_RCPP
}
// shadow_log1m_Spy
Rcpp::S4 shadow_log1m_Spy(Rcpp::S4 x);
RcppExport SEXP _Rshadow_shadow_log1m_Spy(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(shadow_log1m_Spy(x));
    return rcpp_result_gen;
END_RCPP
}
// shadow_exp_Tensor
Rcpp::S4 shadow_exp_Tensor(Rcpp::S4 x);
RcppExport SEXP _Rshadow_shadow_exp_Tensor(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(shadow_exp_Tensor(x));
    return rcpp_result_gen;
END_RCPP
}
// shadow_exp_Spy
Rcpp::S4 shadow_exp_Spy(Rcpp::S4 x);
RcppExport SEXP _Rshadow_shadow_exp_Spy(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(shadow_exp_Spy(x));
    return rcpp_result_gen;
END_RCPP
}
// shadow_lgamma_Tensor
Rcpp::S4 shadow_lgamma_Tensor(Rcpp::S4 x);
RcppExport SEXP _Rshadow_shadow_lgamma_Tensor(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(shadow_lgamma_Tensor(x));
    return rcpp_result_gen;
END_RCPP
}
// shadow_lgamma_Spy
Rcpp::S4 shadow_lgamma_Spy(Rcpp::S4 x);
RcppExport SEXP _Rshadow_shadow_lgamma_Spy(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(shadow_lgamma_Spy(x));
    return rcpp_result_gen;
END_RCPP
}
// shadow_logit_Tensor
Rcpp::S4 shadow_logit_Tensor(Rcpp::S4 x);
RcppExport SEXP _Rshadow_shadow_logit_Tensor(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(shadow_logit_Tensor(x));
    return rcpp_result_gen;
END_RCPP
}
// shadow_logit_Spy
Rcpp::S4 shadow_logit_Spy(Rcpp::S4 x);
RcppExport SEXP _Rshadow_shadow_logit_Spy(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(shadow_logit_Spy(x));
    return rcpp_result_gen;
END_RCPP
}
// shadow_logistic_Tensor
Rcpp::S4 shadow_logistic_Tensor(Rcpp::S4 x);
RcppExport SEXP _Rshadow_shadow_logistic_Tensor(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(shadow_logistic_Tensor(x));
    return rcpp_result_gen;
END_RCPP
}
// shadow_logistic_Spy
Rcpp::S4 shadow_logistic_Spy(Rcpp::S4 x);
RcppExport SEXP _Rshadow_shadow_logistic_Spy(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(shadow_logistic_Spy(x));
    return rcpp_result_gen;
END_RCPP
}
// shadow_sum_Tensor
Rcpp::S4 shadow_sum_Tensor(Rcpp::S4 x);
RcppExport SEXP _Rshadow_shadow_sum_Tensor(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(shadow_sum_Tensor(x));
    return rcpp_result_gen;
END_RCPP
}
// shadow_sum_Spy
Rcpp::S4 shadow_sum_Spy(Rcpp::S4 x);
RcppExport SEXP _Rshadow_shadow_sum_Spy(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(shadow_sum_Spy(x));
    return rcpp_result_gen;
END_RCPP
}
// shadow_sumsq_Tensor
Rcpp::S4 shadow_sumsq_Tensor(Rcpp::S4 x);
RcppExport SEXP _Rshadow_shadow_sumsq_Tensor(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(shadow_sumsq_Tensor(x));
    return rcpp_result_gen;
END_RCPP
}
// shadow_sumsq_Spy
Rcpp::S4 shadow_sumsq_Spy(Rcpp::S4 x);
RcppExport SEXP _Rshadow_shadow_sumsq_Spy(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(shadow_sumsq_Spy(x));
    return rcpp_result_gen;
END_RCPP
}
// shadow_tensor_new
Rcpp::S4 shadow_tensor_new(Rcpp::NumericVector x);
RcppExport SEXP _Rshadow_shadow_tensor_new(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(shadow_tensor_new(x));
    return rcpp_result_gen;
END_RCPP
}
// shadow_tensor_as_numeric
Rcpp::NumericVector shadow_tensor_as_numeric(Rcpp::S4 shadow_tensor);
RcppExport SEXP _Rshadow_shadow_tensor_as_numeric(SEXP shadow_tensorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type shadow_tensor(shadow_tensorSEXP);
    rcpp_result_gen = Rcpp::wrap(shadow_tensor_as_numeric(shadow_tensor));
    return rcpp_result_gen;
END_RCPP
}
// shadow_spy_new
Rcpp::S4 shadow_spy_new(Rcpp::S4 tensor_in, Rcpp::S4 tape_in);
RcppExport SEXP _Rshadow_shadow_spy_new(SEXP tensor_inSEXP, SEXP tape_inSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type tensor_in(tensor_inSEXP);
    Rcpp::traits::input_parameter< Rcpp::S4 >::type tape_in(tape_inSEXP);
    rcpp_result_gen = Rcpp::wrap(shadow_spy_new(tensor_in, tape_in));
    return rcpp_result_gen;
END_RCPP
}
// shadow_spy_as_numeric
Rcpp::NumericVector shadow_spy_as_numeric(Rcpp::S4 shadow_spy);
RcppExport SEXP _Rshadow_shadow_spy_as_numeric(SEXP shadow_spySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type shadow_spy(shadow_spySEXP);
    rcpp_result_gen = Rcpp::wrap(shadow_spy_as_numeric(shadow_spy));
    return rcpp_result_gen;
END_RCPP
}
// shadow_spy_get_trace_index
Rcpp::IntegerVector shadow_spy_get_trace_index(Rcpp::S4 shadow_spy);
RcppExport SEXP _Rshadow_shadow_spy_get_trace_index(SEXP shadow_spySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type shadow_spy(shadow_spySEXP);
    rcpp_result_gen = Rcpp::wrap(shadow_spy_get_trace_index(shadow_spy));
    return rcpp_result_gen;
END_RCPP
}
// shadow_spy_bind_list
Rcpp::S4 shadow_spy_bind_list(Rcpp::List shadow_spy_list);
RcppExport SEXP _Rshadow_shadow_spy_bind_list(SEXP shadow_spy_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type shadow_spy_list(shadow_spy_listSEXP);
    rcpp_result_gen = Rcpp::wrap(shadow_spy_bind_list(shadow_spy_list));
    return rcpp_result_gen;
END_RCPP
}
// shadow_spy_subset_i
Rcpp::S4 shadow_spy_subset_i(Rcpp::S4 spy_in, index_t i);
RcppExport SEXP _Rshadow_shadow_spy_subset_i(SEXP spy_inSEXP, SEXP iSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type spy_in(spy_inSEXP);
    Rcpp::traits::input_parameter< index_t >::type i(iSEXP);
    rcpp_result_gen = Rcpp::wrap(shadow_spy_subset_i(spy_in, i));
    return rcpp_result_gen;
END_RCPP
}
// shadow_spy_subset_i_j
Rcpp::S4 shadow_spy_subset_i_j(Rcpp::S4 spy_in, index_t i, index_t j);
RcppExport SEXP _Rshadow_shadow_spy_subset_i_j(SEXP spy_inSEXP, SEXP iSEXP, SEXP jSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type spy_in(spy_inSEXP);
    Rcpp::traits::input_parameter< index_t >::type i(iSEXP);
    Rcpp::traits::input_parameter< index_t >::type j(jSEXP);
    rcpp_result_gen = Rcpp::wrap(shadow_spy_subset_i_j(spy_in, i, j));
    return rcpp_result_gen;
END_RCPP
}
// shadow_spy_subset_i_j_k
Rcpp::S4 shadow_spy_subset_i_j_k(Rcpp::S4 spy_in, index_t i, index_t j, index_t k);
RcppExport SEXP _Rshadow_shadow_spy_subset_i_j_k(SEXP spy_inSEXP, SEXP iSEXP, SEXP jSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type spy_in(spy_inSEXP);
    Rcpp::traits::input_parameter< index_t >::type i(iSEXP);
    Rcpp::traits::input_parameter< index_t >::type j(jSEXP);
    Rcpp::traits::input_parameter< index_t >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(shadow_spy_subset_i_j_k(spy_in, i, j, k));
    return rcpp_result_gen;
END_RCPP
}
// shadow_spy_read_on_trace
Rcpp::NumericVector shadow_spy_read_on_trace(Rcpp::S4 spy_in, Rcpp::S4 trace_in);
RcppExport SEXP _Rshadow_shadow_spy_read_on_trace(SEXP spy_inSEXP, SEXP trace_inSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type spy_in(spy_inSEXP);
    Rcpp::traits::input_parameter< Rcpp::S4 >::type trace_in(trace_inSEXP);
    rcpp_result_gen = Rcpp::wrap(shadow_spy_read_on_trace(spy_in, trace_in));
    return rcpp_result_gen;
END_RCPP
}
// shadow_tape_new
Rcpp::S4 shadow_tape_new();
RcppExport SEXP _Rshadow_shadow_tape_new() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(shadow_tape_new());
    return rcpp_result_gen;
END_RCPP
}
// shadow_tape_summary
Rcpp::S4 shadow_tape_summary(Rcpp::S4 tape_in);
RcppExport SEXP _Rshadow_shadow_tape_summary(SEXP tape_inSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type tape_in(tape_inSEXP);
    rcpp_result_gen = Rcpp::wrap(shadow_tape_summary(tape_in));
    return rcpp_result_gen;
END_RCPP
}
// shadow_trace_new
Rcpp::S4 shadow_trace_new(Rcpp::S4 tape_in);
RcppExport SEXP _Rshadow_shadow_trace_new(SEXP tape_inSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type tape_in(tape_inSEXP);
    rcpp_result_gen = Rcpp::wrap(shadow_trace_new(tape_in));
    return rcpp_result_gen;
END_RCPP
}
// shadow_trace_values
Rcpp::NumericVector shadow_trace_values(Rcpp::S4 trace_in);
RcppExport SEXP _Rshadow_shadow_trace_values(SEXP trace_inSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type trace_in(trace_inSEXP);
    rcpp_result_gen = Rcpp::wrap(shadow_trace_values(trace_in));
    return rcpp_result_gen;
END_RCPP
}
// shadow_trace_adjoints
Rcpp::NumericVector shadow_trace_adjoints(Rcpp::S4 trace_in);
RcppExport SEXP _Rshadow_shadow_trace_adjoints(SEXP trace_inSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type trace_in(trace_inSEXP);
    rcpp_result_gen = Rcpp::wrap(shadow_trace_adjoints(trace_in));
    return rcpp_result_gen;
END_RCPP
}
// shadow_trace_hessian
Rcpp::NumericVector shadow_trace_hessian(Rcpp::S4 trace_in);
RcppExport SEXP _Rshadow_shadow_trace_hessian(SEXP trace_inSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type trace_in(trace_inSEXP);
    rcpp_result_gen = Rcpp::wrap(shadow_trace_hessian(trace_in));
    return rcpp_result_gen;
END_RCPP
}
// shadow_solver_new
Rcpp::S4 shadow_solver_new(Rcpp::S4 trace_in);
RcppExport SEXP _Rshadow_shadow_solver_new(SEXP trace_inSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type trace_in(trace_inSEXP);
    rcpp_result_gen = Rcpp::wrap(shadow_solver_new(trace_in));
    return rcpp_result_gen;
END_RCPP
}
// shadow_extract_solver_config
Rcpp::S4 shadow_extract_solver_config(Rcpp::S4 solver_in);
RcppExport SEXP _Rshadow_shadow_extract_solver_config(SEXP solver_inSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type solver_in(solver_inSEXP);
    rcpp_result_gen = Rcpp::wrap(shadow_extract_solver_config(solver_in));
    return rcpp_result_gen;
END_RCPP
}
// shadow_solver_config_new
Rcpp::S4 shadow_solver_config_new();
RcppExport SEXP _Rshadow_shadow_solver_config_new() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(shadow_solver_config_new());
    return rcpp_result_gen;
END_RCPP
}
// shadow_get_solver_with_config
Rcpp::S4 shadow_get_solver_with_config(Rcpp::S4 trace_in, Rcpp::S4 config_in);
RcppExport SEXP _Rshadow_shadow_get_solver_with_config(SEXP trace_inSEXP, SEXP config_inSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type trace_in(trace_inSEXP);
    Rcpp::traits::input_parameter< Rcpp::S4 >::type config_in(config_inSEXP);
    rcpp_result_gen = Rcpp::wrap(shadow_get_solver_with_config(trace_in, config_in));
    return rcpp_result_gen;
END_RCPP
}
// shadow_extract_solver_states
Rcpp::List shadow_extract_solver_states(Rcpp::S4 solver_in);
RcppExport SEXP _Rshadow_shadow_extract_solver_states(SEXP solver_inSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type solver_in(solver_inSEXP);
    rcpp_result_gen = Rcpp::wrap(shadow_extract_solver_states(solver_in));
    return rcpp_result_gen;
END_RCPP
}
// shadow_solver_maximize
Rcpp::S4 shadow_solver_maximize(Rcpp::S4 solver_in);
RcppExport SEXP _Rshadow_shadow_solver_maximize(SEXP solver_inSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type solver_in(solver_inSEXP);
    rcpp_result_gen = Rcpp::wrap(shadow_solver_maximize(solver_in));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_Rshadow_shadow_plus_Tensor_Tensor", (DL_FUNC) &_Rshadow_shadow_plus_Tensor_Tensor, 2},
    {"_Rshadow_shadow_plus_Tensor_Spy", (DL_FUNC) &_Rshadow_shadow_plus_Tensor_Spy, 2},
    {"_Rshadow_shadow_plus_Spy_Tensor", (DL_FUNC) &_Rshadow_shadow_plus_Spy_Tensor, 2},
    {"_Rshadow_shadow_plus_Spy_Spy", (DL_FUNC) &_Rshadow_shadow_plus_Spy_Spy, 2},
    {"_Rshadow_shadow_minus_Tensor_Tensor", (DL_FUNC) &_Rshadow_shadow_minus_Tensor_Tensor, 2},
    {"_Rshadow_shadow_minus_Tensor_Spy", (DL_FUNC) &_Rshadow_shadow_minus_Tensor_Spy, 2},
    {"_Rshadow_shadow_minus_Spy_Tensor", (DL_FUNC) &_Rshadow_shadow_minus_Spy_Tensor, 2},
    {"_Rshadow_shadow_minus_Spy_Spy", (DL_FUNC) &_Rshadow_shadow_minus_Spy_Spy, 2},
    {"_Rshadow_shadow_multiplies_Tensor_Tensor", (DL_FUNC) &_Rshadow_shadow_multiplies_Tensor_Tensor, 2},
    {"_Rshadow_shadow_multiplies_Tensor_Spy", (DL_FUNC) &_Rshadow_shadow_multiplies_Tensor_Spy, 2},
    {"_Rshadow_shadow_multiplies_Spy_Tensor", (DL_FUNC) &_Rshadow_shadow_multiplies_Spy_Tensor, 2},
    {"_Rshadow_shadow_multiplies_Spy_Spy", (DL_FUNC) &_Rshadow_shadow_multiplies_Spy_Spy, 2},
    {"_Rshadow_shadow_divides_Tensor_Tensor", (DL_FUNC) &_Rshadow_shadow_divides_Tensor_Tensor, 2},
    {"_Rshadow_shadow_divides_Tensor_Spy", (DL_FUNC) &_Rshadow_shadow_divides_Tensor_Spy, 2},
    {"_Rshadow_shadow_divides_Spy_Tensor", (DL_FUNC) &_Rshadow_shadow_divides_Spy_Tensor, 2},
    {"_Rshadow_shadow_divides_Spy_Spy", (DL_FUNC) &_Rshadow_shadow_divides_Spy_Spy, 2},
    {"_Rshadow_shadow_less_Tensor_Tensor", (DL_FUNC) &_Rshadow_shadow_less_Tensor_Tensor, 2},
    {"_Rshadow_shadow_less_Tensor_Spy", (DL_FUNC) &_Rshadow_shadow_less_Tensor_Spy, 2},
    {"_Rshadow_shadow_less_Spy_Tensor", (DL_FUNC) &_Rshadow_shadow_less_Spy_Tensor, 2},
    {"_Rshadow_shadow_less_Spy_Spy", (DL_FUNC) &_Rshadow_shadow_less_Spy_Spy, 2},
    {"_Rshadow_shadow_less_equal_Tensor_Tensor", (DL_FUNC) &_Rshadow_shadow_less_equal_Tensor_Tensor, 2},
    {"_Rshadow_shadow_less_equal_Tensor_Spy", (DL_FUNC) &_Rshadow_shadow_less_equal_Tensor_Spy, 2},
    {"_Rshadow_shadow_less_equal_Spy_Tensor", (DL_FUNC) &_Rshadow_shadow_less_equal_Spy_Tensor, 2},
    {"_Rshadow_shadow_less_equal_Spy_Spy", (DL_FUNC) &_Rshadow_shadow_less_equal_Spy_Spy, 2},
    {"_Rshadow_shadow_greater_Tensor_Tensor", (DL_FUNC) &_Rshadow_shadow_greater_Tensor_Tensor, 2},
    {"_Rshadow_shadow_greater_Tensor_Spy", (DL_FUNC) &_Rshadow_shadow_greater_Tensor_Spy, 2},
    {"_Rshadow_shadow_greater_Spy_Tensor", (DL_FUNC) &_Rshadow_shadow_greater_Spy_Tensor, 2},
    {"_Rshadow_shadow_greater_Spy_Spy", (DL_FUNC) &_Rshadow_shadow_greater_Spy_Spy, 2},
    {"_Rshadow_shadow_greater_equal_Tensor_Tensor", (DL_FUNC) &_Rshadow_shadow_greater_equal_Tensor_Tensor, 2},
    {"_Rshadow_shadow_greater_equal_Tensor_Spy", (DL_FUNC) &_Rshadow_shadow_greater_equal_Tensor_Spy, 2},
    {"_Rshadow_shadow_greater_equal_Spy_Tensor", (DL_FUNC) &_Rshadow_shadow_greater_equal_Spy_Tensor, 2},
    {"_Rshadow_shadow_greater_equal_Spy_Spy", (DL_FUNC) &_Rshadow_shadow_greater_equal_Spy_Spy, 2},
    {"_Rshadow_shadow_pow_Tensor_Tensor", (DL_FUNC) &_Rshadow_shadow_pow_Tensor_Tensor, 2},
    {"_Rshadow_shadow_pow_Tensor_Spy", (DL_FUNC) &_Rshadow_shadow_pow_Tensor_Spy, 2},
    {"_Rshadow_shadow_pow_Spy_Tensor", (DL_FUNC) &_Rshadow_shadow_pow_Spy_Tensor, 2},
    {"_Rshadow_shadow_pow_Spy_Spy", (DL_FUNC) &_Rshadow_shadow_pow_Spy_Spy, 2},
    {"_Rshadow_shadow_dot_Tensor_Tensor", (DL_FUNC) &_Rshadow_shadow_dot_Tensor_Tensor, 2},
    {"_Rshadow_shadow_dot_Tensor_Spy", (DL_FUNC) &_Rshadow_shadow_dot_Tensor_Spy, 2},
    {"_Rshadow_shadow_dot_Spy_Tensor", (DL_FUNC) &_Rshadow_shadow_dot_Spy_Tensor, 2},
    {"_Rshadow_shadow_dot_Spy_Spy", (DL_FUNC) &_Rshadow_shadow_dot_Spy_Spy, 2},
    {"_Rshadow_shadow_sumlogbern_Tensor_Tensor", (DL_FUNC) &_Rshadow_shadow_sumlogbern_Tensor_Tensor, 2},
    {"_Rshadow_shadow_sumlogbern_Spy_Tensor", (DL_FUNC) &_Rshadow_shadow_sumlogbern_Spy_Tensor, 2},
    {"_Rshadow_shadow_matmult_Tensor_Tensor", (DL_FUNC) &_Rshadow_shadow_matmult_Tensor_Tensor, 2},
    {"_Rshadow_shadow_matmult_Tensor_Spy", (DL_FUNC) &_Rshadow_shadow_matmult_Tensor_Spy, 2},
    {"_Rshadow_shadow_matmult_Spy_Tensor", (DL_FUNC) &_Rshadow_shadow_matmult_Spy_Tensor, 2},
    {"_Rshadow_shadow_matmult_Spy_Spy", (DL_FUNC) &_Rshadow_shadow_matmult_Spy_Spy, 2},
    {"_Rshadow_shadow_negate_Tensor", (DL_FUNC) &_Rshadow_shadow_negate_Tensor, 1},
    {"_Rshadow_shadow_negate_Spy", (DL_FUNC) &_Rshadow_shadow_negate_Spy, 1},
    {"_Rshadow_shadow_log_Tensor", (DL_FUNC) &_Rshadow_shadow_log_Tensor, 1},
    {"_Rshadow_shadow_log_Spy", (DL_FUNC) &_Rshadow_shadow_log_Spy, 1},
    {"_Rshadow_shadow_log1p_Tensor", (DL_FUNC) &_Rshadow_shadow_log1p_Tensor, 1},
    {"_Rshadow_shadow_log1p_Spy", (DL_FUNC) &_Rshadow_shadow_log1p_Spy, 1},
    {"_Rshadow_shadow_log1m_Tensor", (DL_FUNC) &_Rshadow_shadow_log1m_Tensor, 1},
    {"_Rshadow_shadow_log1m_Spy", (DL_FUNC) &_Rshadow_shadow_log1m_Spy, 1},
    {"_Rshadow_shadow_exp_Tensor", (DL_FUNC) &_Rshadow_shadow_exp_Tensor, 1},
    {"_Rshadow_shadow_exp_Spy", (DL_FUNC) &_Rshadow_shadow_exp_Spy, 1},
    {"_Rshadow_shadow_lgamma_Tensor", (DL_FUNC) &_Rshadow_shadow_lgamma_Tensor, 1},
    {"_Rshadow_shadow_lgamma_Spy", (DL_FUNC) &_Rshadow_shadow_lgamma_Spy, 1},
    {"_Rshadow_shadow_logit_Tensor", (DL_FUNC) &_Rshadow_shadow_logit_Tensor, 1},
    {"_Rshadow_shadow_logit_Spy", (DL_FUNC) &_Rshadow_shadow_logit_Spy, 1},
    {"_Rshadow_shadow_logistic_Tensor", (DL_FUNC) &_Rshadow_shadow_logistic_Tensor, 1},
    {"_Rshadow_shadow_logistic_Spy", (DL_FUNC) &_Rshadow_shadow_logistic_Spy, 1},
    {"_Rshadow_shadow_sum_Tensor", (DL_FUNC) &_Rshadow_shadow_sum_Tensor, 1},
    {"_Rshadow_shadow_sum_Spy", (DL_FUNC) &_Rshadow_shadow_sum_Spy, 1},
    {"_Rshadow_shadow_sumsq_Tensor", (DL_FUNC) &_Rshadow_shadow_sumsq_Tensor, 1},
    {"_Rshadow_shadow_sumsq_Spy", (DL_FUNC) &_Rshadow_shadow_sumsq_Spy, 1},
    {"_Rshadow_shadow_tensor_new", (DL_FUNC) &_Rshadow_shadow_tensor_new, 1},
    {"_Rshadow_shadow_tensor_as_numeric", (DL_FUNC) &_Rshadow_shadow_tensor_as_numeric, 1},
    {"_Rshadow_shadow_spy_new", (DL_FUNC) &_Rshadow_shadow_spy_new, 2},
    {"_Rshadow_shadow_spy_as_numeric", (DL_FUNC) &_Rshadow_shadow_spy_as_numeric, 1},
    {"_Rshadow_shadow_spy_get_trace_index", (DL_FUNC) &_Rshadow_shadow_spy_get_trace_index, 1},
    {"_Rshadow_shadow_spy_bind_list", (DL_FUNC) &_Rshadow_shadow_spy_bind_list, 1},
    {"_Rshadow_shadow_spy_subset_i", (DL_FUNC) &_Rshadow_shadow_spy_subset_i, 2},
    {"_Rshadow_shadow_spy_subset_i_j", (DL_FUNC) &_Rshadow_shadow_spy_subset_i_j, 3},
    {"_Rshadow_shadow_spy_subset_i_j_k", (DL_FUNC) &_Rshadow_shadow_spy_subset_i_j_k, 4},
    {"_Rshadow_shadow_spy_read_on_trace", (DL_FUNC) &_Rshadow_shadow_spy_read_on_trace, 2},
    {"_Rshadow_shadow_tape_new", (DL_FUNC) &_Rshadow_shadow_tape_new, 0},
    {"_Rshadow_shadow_tape_summary", (DL_FUNC) &_Rshadow_shadow_tape_summary, 1},
    {"_Rshadow_shadow_trace_new", (DL_FUNC) &_Rshadow_shadow_trace_new, 1},
    {"_Rshadow_shadow_trace_values", (DL_FUNC) &_Rshadow_shadow_trace_values, 1},
    {"_Rshadow_shadow_trace_adjoints", (DL_FUNC) &_Rshadow_shadow_trace_adjoints, 1},
    {"_Rshadow_shadow_trace_hessian", (DL_FUNC) &_Rshadow_shadow_trace_hessian, 1},
    {"_Rshadow_shadow_solver_new", (DL_FUNC) &_Rshadow_shadow_solver_new, 1},
    {"_Rshadow_shadow_extract_solver_config", (DL_FUNC) &_Rshadow_shadow_extract_solver_config, 1},
    {"_Rshadow_shadow_solver_config_new", (DL_FUNC) &_Rshadow_shadow_solver_config_new, 0},
    {"_Rshadow_shadow_get_solver_with_config", (DL_FUNC) &_Rshadow_shadow_get_solver_with_config, 2},
    {"_Rshadow_shadow_extract_solver_states", (DL_FUNC) &_Rshadow_shadow_extract_solver_states, 1},
    {"_Rshadow_shadow_solver_maximize", (DL_FUNC) &_Rshadow_shadow_solver_maximize, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_Rshadow(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
