# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.shadow_plus_Tensor_Tensor <- function(left, right) {
    .Call(`_Rshadow_shadow_plus_Tensor_Tensor`, left, right)
}

.shadow_plus_Tensor_Spy <- function(left, right) {
    .Call(`_Rshadow_shadow_plus_Tensor_Spy`, left, right)
}

.shadow_plus_Spy_Tensor <- function(left, right) {
    .Call(`_Rshadow_shadow_plus_Spy_Tensor`, left, right)
}

.shadow_plus_Spy_Spy <- function(left, right) {
    .Call(`_Rshadow_shadow_plus_Spy_Spy`, left, right)
}

.shadow_minus_Tensor_Tensor <- function(left, right) {
    .Call(`_Rshadow_shadow_minus_Tensor_Tensor`, left, right)
}

.shadow_minus_Tensor_Spy <- function(left, right) {
    .Call(`_Rshadow_shadow_minus_Tensor_Spy`, left, right)
}

.shadow_minus_Spy_Tensor <- function(left, right) {
    .Call(`_Rshadow_shadow_minus_Spy_Tensor`, left, right)
}

.shadow_minus_Spy_Spy <- function(left, right) {
    .Call(`_Rshadow_shadow_minus_Spy_Spy`, left, right)
}

.shadow_multiplies_Tensor_Tensor <- function(left, right) {
    .Call(`_Rshadow_shadow_multiplies_Tensor_Tensor`, left, right)
}

.shadow_multiplies_Tensor_Spy <- function(left, right) {
    .Call(`_Rshadow_shadow_multiplies_Tensor_Spy`, left, right)
}

.shadow_multiplies_Spy_Tensor <- function(left, right) {
    .Call(`_Rshadow_shadow_multiplies_Spy_Tensor`, left, right)
}

.shadow_multiplies_Spy_Spy <- function(left, right) {
    .Call(`_Rshadow_shadow_multiplies_Spy_Spy`, left, right)
}

.shadow_divides_Tensor_Tensor <- function(left, right) {
    .Call(`_Rshadow_shadow_divides_Tensor_Tensor`, left, right)
}

.shadow_divides_Tensor_Spy <- function(left, right) {
    .Call(`_Rshadow_shadow_divides_Tensor_Spy`, left, right)
}

.shadow_divides_Spy_Tensor <- function(left, right) {
    .Call(`_Rshadow_shadow_divides_Spy_Tensor`, left, right)
}

.shadow_divides_Spy_Spy <- function(left, right) {
    .Call(`_Rshadow_shadow_divides_Spy_Spy`, left, right)
}

.shadow_less_Tensor_Tensor <- function(left, right) {
    .Call(`_Rshadow_shadow_less_Tensor_Tensor`, left, right)
}

.shadow_less_Tensor_Spy <- function(left, right) {
    .Call(`_Rshadow_shadow_less_Tensor_Spy`, left, right)
}

.shadow_less_Spy_Tensor <- function(left, right) {
    .Call(`_Rshadow_shadow_less_Spy_Tensor`, left, right)
}

.shadow_less_Spy_Spy <- function(left, right) {
    .Call(`_Rshadow_shadow_less_Spy_Spy`, left, right)
}

.shadow_less_equal_Tensor_Tensor <- function(left, right) {
    .Call(`_Rshadow_shadow_less_equal_Tensor_Tensor`, left, right)
}

.shadow_less_equal_Tensor_Spy <- function(left, right) {
    .Call(`_Rshadow_shadow_less_equal_Tensor_Spy`, left, right)
}

.shadow_less_equal_Spy_Tensor <- function(left, right) {
    .Call(`_Rshadow_shadow_less_equal_Spy_Tensor`, left, right)
}

.shadow_less_equal_Spy_Spy <- function(left, right) {
    .Call(`_Rshadow_shadow_less_equal_Spy_Spy`, left, right)
}

.shadow_greater_Tensor_Tensor <- function(left, right) {
    .Call(`_Rshadow_shadow_greater_Tensor_Tensor`, left, right)
}

.shadow_greater_Tensor_Spy <- function(left, right) {
    .Call(`_Rshadow_shadow_greater_Tensor_Spy`, left, right)
}

.shadow_greater_Spy_Tensor <- function(left, right) {
    .Call(`_Rshadow_shadow_greater_Spy_Tensor`, left, right)
}

.shadow_greater_Spy_Spy <- function(left, right) {
    .Call(`_Rshadow_shadow_greater_Spy_Spy`, left, right)
}

.shadow_greater_equal_Tensor_Tensor <- function(left, right) {
    .Call(`_Rshadow_shadow_greater_equal_Tensor_Tensor`, left, right)
}

.shadow_greater_equal_Tensor_Spy <- function(left, right) {
    .Call(`_Rshadow_shadow_greater_equal_Tensor_Spy`, left, right)
}

.shadow_greater_equal_Spy_Tensor <- function(left, right) {
    .Call(`_Rshadow_shadow_greater_equal_Spy_Tensor`, left, right)
}

.shadow_greater_equal_Spy_Spy <- function(left, right) {
    .Call(`_Rshadow_shadow_greater_equal_Spy_Spy`, left, right)
}

.shadow_pow_Tensor_Tensor <- function(left, right) {
    .Call(`_Rshadow_shadow_pow_Tensor_Tensor`, left, right)
}

.shadow_pow_Tensor_Spy <- function(left, right) {
    .Call(`_Rshadow_shadow_pow_Tensor_Spy`, left, right)
}

.shadow_pow_Spy_Tensor <- function(left, right) {
    .Call(`_Rshadow_shadow_pow_Spy_Tensor`, left, right)
}

.shadow_pow_Spy_Spy <- function(left, right) {
    .Call(`_Rshadow_shadow_pow_Spy_Spy`, left, right)
}

.shadow_dot_Tensor_Tensor <- function(left, right) {
    .Call(`_Rshadow_shadow_dot_Tensor_Tensor`, left, right)
}

.shadow_dot_Tensor_Spy <- function(left, right) {
    .Call(`_Rshadow_shadow_dot_Tensor_Spy`, left, right)
}

.shadow_dot_Spy_Tensor <- function(left, right) {
    .Call(`_Rshadow_shadow_dot_Spy_Tensor`, left, right)
}

.shadow_dot_Spy_Spy <- function(left, right) {
    .Call(`_Rshadow_shadow_dot_Spy_Spy`, left, right)
}

.shadow_sumlogbern_Tensor_Tensor <- function(left, right) {
    .Call(`_Rshadow_shadow_sumlogbern_Tensor_Tensor`, left, right)
}

.shadow_sumlogbern_Spy_Tensor <- function(left, right) {
    .Call(`_Rshadow_shadow_sumlogbern_Spy_Tensor`, left, right)
}

.shadow_matmult_Tensor_Tensor <- function(left, right) {
    .Call(`_Rshadow_shadow_matmult_Tensor_Tensor`, left, right)
}

.shadow_matmult_Tensor_Spy <- function(left, right) {
    .Call(`_Rshadow_shadow_matmult_Tensor_Spy`, left, right)
}

.shadow_matmult_Spy_Tensor <- function(left, right) {
    .Call(`_Rshadow_shadow_matmult_Spy_Tensor`, left, right)
}

.shadow_matmult_Spy_Spy <- function(left, right) {
    .Call(`_Rshadow_shadow_matmult_Spy_Spy`, left, right)
}

.shadow_negate_Tensor <- function(x) {
    .Call(`_Rshadow_shadow_negate_Tensor`, x)
}

.shadow_negate_Spy <- function(x) {
    .Call(`_Rshadow_shadow_negate_Spy`, x)
}

.shadow_log_Tensor <- function(x) {
    .Call(`_Rshadow_shadow_log_Tensor`, x)
}

.shadow_log_Spy <- function(x) {
    .Call(`_Rshadow_shadow_log_Spy`, x)
}

.shadow_log1p_Tensor <- function(x) {
    .Call(`_Rshadow_shadow_log1p_Tensor`, x)
}

.shadow_log1p_Spy <- function(x) {
    .Call(`_Rshadow_shadow_log1p_Spy`, x)
}

.shadow_log1m_Tensor <- function(x) {
    .Call(`_Rshadow_shadow_log1m_Tensor`, x)
}

.shadow_log1m_Spy <- function(x) {
    .Call(`_Rshadow_shadow_log1m_Spy`, x)
}

.shadow_exp_Tensor <- function(x) {
    .Call(`_Rshadow_shadow_exp_Tensor`, x)
}

.shadow_exp_Spy <- function(x) {
    .Call(`_Rshadow_shadow_exp_Spy`, x)
}

.shadow_lgamma_Tensor <- function(x) {
    .Call(`_Rshadow_shadow_lgamma_Tensor`, x)
}

.shadow_lgamma_Spy <- function(x) {
    .Call(`_Rshadow_shadow_lgamma_Spy`, x)
}

.shadow_logit_Tensor <- function(x) {
    .Call(`_Rshadow_shadow_logit_Tensor`, x)
}

.shadow_logit_Spy <- function(x) {
    .Call(`_Rshadow_shadow_logit_Spy`, x)
}

.shadow_logistic_Tensor <- function(x) {
    .Call(`_Rshadow_shadow_logistic_Tensor`, x)
}

.shadow_logistic_Spy <- function(x) {
    .Call(`_Rshadow_shadow_logistic_Spy`, x)
}

.shadow_sum_Tensor <- function(x) {
    .Call(`_Rshadow_shadow_sum_Tensor`, x)
}

.shadow_sum_Spy <- function(x) {
    .Call(`_Rshadow_shadow_sum_Spy`, x)
}

.shadow_sumsq_Tensor <- function(x) {
    .Call(`_Rshadow_shadow_sumsq_Tensor`, x)
}

.shadow_sumsq_Spy <- function(x) {
    .Call(`_Rshadow_shadow_sumsq_Spy`, x)
}

.shadow_tensor_new <- function(x) {
    .Call(`_Rshadow_shadow_tensor_new`, x)
}

.shadow_tensor_as_numeric <- function(shadow_tensor) {
    .Call(`_Rshadow_shadow_tensor_as_numeric`, shadow_tensor)
}

.shadow_spy_new <- function(tensor_in, tape_in) {
    .Call(`_Rshadow_shadow_spy_new`, tensor_in, tape_in)
}

.shadow_spy_as_numeric <- function(shadow_spy) {
    .Call(`_Rshadow_shadow_spy_as_numeric`, shadow_spy)
}

.shadow_spy_get_trace_index <- function(shadow_spy) {
    .Call(`_Rshadow_shadow_spy_get_trace_index`, shadow_spy)
}

shadow_spy_bind_list <- function(shadow_spy_list) {
    .Call(`_Rshadow_shadow_spy_bind_list`, shadow_spy_list)
}

.shadow_spy_subset_i <- function(spy_in, i) {
    .Call(`_Rshadow_shadow_spy_subset_i`, spy_in, i)
}

.shadow_spy_subset_i_j <- function(spy_in, i, j) {
    .Call(`_Rshadow_shadow_spy_subset_i_j`, spy_in, i, j)
}

.shadow_spy_subset_i_j_k <- function(spy_in, i, j, k) {
    .Call(`_Rshadow_shadow_spy_subset_i_j_k`, spy_in, i, j, k)
}

.shadow_spy_read_on_trace <- function(spy_in, trace_in) {
    .Call(`_Rshadow_shadow_spy_read_on_trace`, spy_in, trace_in)
}

.shadow_tape_new <- function() {
    .Call(`_Rshadow_shadow_tape_new`)
}

shadow_tape_summary <- function(tape_in) {
    .Call(`_Rshadow_shadow_tape_summary`, tape_in)
}

shadow_trace_new <- function(tape_in) {
    .Call(`_Rshadow_shadow_trace_new`, tape_in)
}

shadow_trace_values <- function(trace_in) {
    .Call(`_Rshadow_shadow_trace_values`, trace_in)
}

shadow_trace_adjoints <- function(trace_in) {
    .Call(`_Rshadow_shadow_trace_adjoints`, trace_in)
}

.shadow_trace_hessian <- function(trace_in) {
    .Call(`_Rshadow_shadow_trace_hessian`, trace_in)
}

.shadow_solver_new <- function(trace_in) {
    .Call(`_Rshadow_shadow_solver_new`, trace_in)
}

shadow_extract_solver_config <- function(solver_in) {
    .Call(`_Rshadow_shadow_extract_solver_config`, solver_in)
}

shadow_solver_config_new <- function() {
    .Call(`_Rshadow_shadow_solver_config_new`)
}

.shadow_get_solver_with_config <- function(trace_in, config_in) {
    .Call(`_Rshadow_shadow_get_solver_with_config`, trace_in, config_in)
}

shadow_extract_solver_states <- function(solver_in) {
    .Call(`_Rshadow_shadow_extract_solver_states`, solver_in)
}

shadow_solver_maximize <- function(solver_in) {
    .Call(`_Rshadow_shadow_solver_maximize`, solver_in)
}

